# fly.toml file generated for battlesnack on 2022-10-26T23:40:28+02:00

app = "battlesnack"
kill_signal = "SIGINT"
kill_timeout = 5

[experimental]
  cmd = ["./topsnek-server", "0.0.0.0"]

[[services]]
  internal_port = 5110
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "5110"
    restart_limit = 6
    timeout = "2s"
